#开发环境配置
server:
  port: 8083   #端口
spring:     #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/xingli?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    maximum-pool-size: 30
  #日志
logging:
  config: classpath:logback.xml
  path: D:\logs\comadmin